# name: Sample Project

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
#   workflow_dispatch: {}

# env:
#   GITHUB_WORKFLOW_RUN_ID: "${{ github.ref_name }}.${{ github.run_id }}"
#   service: "sample-project"
#   AZURE_WEBAPP_NAME: "sampleproject"
#   AZURE_WEBAPP_NAME1: "aditya-test"

# jobs:
#   build-sample-project:
#     name: build-sample-project
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Set up JDK 11
#       uses: actions/setup-java@v4
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file

# #     - uses: actions/checkout@v4
# #     - name: Set up JDK 11
# #       uses: actions/setup-java@v4
# #       with:
# #         java-version: '11'
# #         distribution: 'temurin'
# #         server-id: github   
# #         cache: maven

# #     - name: Build with Maven
# #       run: mvn --batch-mode --file ./pom.xml dependency:purge-local-repository clean package deploy
# #       env:
# #         user_name: ${{ secrets.USER_NAME }}
# #         user_token: ${{ secrets.USER_TOKEN }}

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

#     - name: Maven Deploy 
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}

#     - name: Upload JAR artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: sample-project-0.0.1-SNAPSHOT
#         path: target/*.jar       
 
#   deploy-sample-project:
#     permissions:
#       contents: none
#       packages: write
#     runs-on: ubuntu-latest
#     needs: build-sample-project
#     environment:
#       name: 'test'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Login to Azure
#       uses: azure/login@v2
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Download artifact from build job
#       uses: actions/download-artifact@v3
#       with:
#         name: sample-project-0.0.1-SNAPSHOT

#     - name: copy JAR to Azure Blob Storage
#       uses: azure/cli@v1
#       env:
#         AZURE_STORAGE_ACCOUNT_NAME: "addyxlr8"
#         AZURE_STORAGE_CONTAINER_NAME: "sampleproject"
#       with:
#         inlineScript: |          
#           # Upload JAR file
#           az storage blob upload \
#             --overwrite \
#             --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} \
#             --container-name ${{ env.AZURE_STORAGE_CONTAINER_NAME }} \
#             --name sample-project-0.0.1-SNAPSHOT.jar \
#             --file sample-project-0.0.1-SNAPSHOT.jar
            
#     # - name: Download artifact from build job
#     #   uses: actions/download-artifact@v3
#     #   with:
#     #     name: sample-project-0.0.1-SNAPSHOT

#     - name: Deploy to Azure Web App
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: 'sample-project-0.0.1-SNAPSHOT.jar'

#     - name: Deploy to Function App
#       id: deploy-to-functionapp
#       uses: azure/functions-action@v1
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME1 }}
#         publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
#         package: 'sample-project-0.0.1-SNAPSHOT.jar'


name: Sample Project
# here we are mentioning that whenever there is code committed and pushed from master automatically start the pipeline.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}
# we have declared the environment variables 
env:
#the env variable GITHUB_WORKFLOW_RUN_ID is predefined
  GITHUB_WORKFLOW_RUN_ID: "${{ github.ref_name }}.${{ github.run_id }}"
# we are giving the name of the service
  service: "sample-project"
  AZURE_WEBAPP_NAME: "sampleproject"
# we will declare the jobs to be done
jobs:
  build-sample-project:
    name: build-sample-project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file



    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Maven Deploy 
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
# we will upload the artefact to github packages
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: sample-project-0.0.1-SNAPSHOT
        path: target/*.jar       
 

# we are deploying the application to azure webapp
  deploy-sample-project:
    permissions:
      contents: none
      packages: write
    runs-on: ubuntu-latest
    needs: build-sample-project
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#credential are stored in github secrets
    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
# we have created a azure storage and created the blob container the jar artifact will be saved in it. We can download from the blob container
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: sample-project-0.0.1-SNAPSHOT
# we copy the jar file to azure blob storage 
    - name: copy JAR to Azure Blob Storage
      uses: azure/cli@v1
      env:
        AZURE_STORAGE_ACCOUNT_NAME: "addyxlr8"
        AZURE_STORAGE_CONTAINER_NAME: "sampleproject"
      with:
        inlineScript: |          
          # Upload JAR file
          az storage blob upload \
            --overwrite \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name ${{ env.AZURE_STORAGE_CONTAINER_NAME }} \
            --name sample-project-0.0.1-SNAPSHOT.jar \
            --file sample-project-0.0.1-SNAPSHOT.jar
            
   

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'sample-project-0.0.1-SNAPSHOT.jar'
